### PR TITLE
Differenciate between directory or file

### PR DESCRIPTION
**Pull request by CadencePrestissimo**

### CODE REVIEW

**Comment by untrulynoxiusmj** [comment]
error

@CadencePrestissimo I am getting this error
Also please attach a screenshot of the output you are getting

**Comment by untrulynoxiusmj** [comment]
Please squash the commits

**Comment by CadencePrestissimo** [comment]
Resolving conflicts is adding a commit, Should I make a new branch then commit ?

**Comment by untrulynoxiusmj** [comment]
Do you mean : make a new PR ?
you can do that for now 
But I recommend squashing the commits

**Comment by CadencePrestissimo** [comment]
i  have created a new branch , the commits are not getting sqaushed

**Comment by untrulynoxiusmj** [comment]
@CadencePrestissimo  attach the screenshot of your output

**Pull request closed without merging**
