### PR TITLE
succesful  in adding different buttons

### PR DESCRIPTION
**Pull request by Parasagrawal**
Capture

### CODE REVIEW

**Comment by untrulynoxiusmj** [comment]
@Parasagrawal give suitable id's to different elements you have added
like id = go-back
Also anchor tag will do the job, but can you think of a better tag (element)
Although good work, but can be improved
like we already have style.css, so there's no point in styling an element in html file only
you should do it in style.css. (styling can be improved)
One more thing :
as you can observe with the title bar that it is sticky and no scrollbar in the region of title bar
We need the same thing for navigation bar

**Review by Parasagrawal — COMMENTED** [review]
Capture

**Comment by Parasagrawal** [comment]
the replacement of anchor tag is onclick button which is part of javascript, so i have not used.
let me know if we can use some other tag.

**Comment by untrulynoxiusmj** [comment]
@Parasagrawal squash the commits

**Pull request merged**
