### PR TITLE
Fixes issue #1 Added a Title Bar for File Explorer

### PR DESCRIPTION
**Pull request by AlacritousCreature**
issue #1 
Added Title Bar in File Explorer

it looks like this

Screenshot (237)

### CODE REVIEW

**Comment by AlacritousCreature** [comment]
Hey @untrulynoxiusmj ! please review it.....if it is ok or some changes are to made.

**Comment by untrulynoxiusmj** [comment]
1g
2g
@AlacritousCreature There are problems with the name of app (not responsive)

**Comment by untrulynoxiusmj** [comment]
@AlacritousCreature Also please squash your commits

**Comment by AlacritousCreature** [comment]
oh....okay.

**Comment by AlacritousCreature** [comment]
oh....okay!

**Comment by AlacritousCreature** [comment]
Hey! I am unable to squash them....i'll close this pr and make a new one with one commit.

**Pull request closed without merging**
